// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Explains a prescription in plain language.
 *
 * - explainPrescription - A function that handles the prescription explanation process.
 * - ExplainPrescriptionInput - The input type for the explainPrescription function.
 * - ExplainPrescriptionOutput - The return type for the explainPrescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainPrescriptionInputSchema = z.object({
  prescriptionImage: z
    .string()
    .describe(
      "A photo of a prescription, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ExplainPrescriptionInput = z.infer<typeof ExplainPrescriptionInputSchema>;

const ExplainPrescriptionOutputSchema = z.object({
  explanation: z.string().describe('A plain language explanation of the prescription.'),
  dosage: z.string().describe('The dosage of the medication.'),
  frequency: z.string().describe('How often the medication should be taken.'),
  potentialSideEffects: z.string().describe('Potential side effects of the medication.'),
});
export type ExplainPrescriptionOutput = z.infer<typeof ExplainPrescriptionOutputSchema>;

export async function explainPrescription(input: ExplainPrescriptionInput): Promise<ExplainPrescriptionOutput> {
  return explainPrescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainPrescriptionPrompt',
  input: {schema: ExplainPrescriptionInputSchema},
  output: {schema: ExplainPrescriptionOutputSchema},
  prompt: `You are a pharmacist explaining a prescription to a caregiver.

You will receive an image of the prescription. Use OCR to extract the text from the image.

Then, provide a plain language explanation of the prescription, including the dosage, frequency, and potential side effects.

Image: {{media url=prescriptionImage}}

Explanation: {
    explanation,
    dosage,
    frequency,
    potentialSideEffects
}`, //The JSON should not be escaped, it is a Typescript file.
});

const explainPrescriptionFlow = ai.defineFlow(
  {
    name: 'explainPrescriptionFlow',
    inputSchema: ExplainPrescriptionInputSchema,
    outputSchema: ExplainPrescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
